# Generated by Django 5.1.2 on 2025-04-13 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='estoque',
            field=models.IntegerField(default=0),
        ),
    ]
