# Generated by Django 5.1.2 on 2025-04-13 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='valor',
            field=models.FloatField(default=0.0),
        ),
    ]
