# Generated by Django 5.2.3 on 2025-07-08 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_pedido_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='jogos/'),
        ),
    ]
